services:
  backend:
    image: openjdk:8-jdk-alpine
    container_name: aicare_backend
    working_dir: /app
    volumes:
      - ./AICare:/app
    ports:
      - "8080:8080"
    command: sh -c "apk add --no-cache maven && mvn clean install && java -jar target/AICare-0.0.1-SNAPSHOT.jar"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/aicare
      - SPRING_DATASOURCE_USERNAME=aicareuser
      - SPRING_DATASOURCE_PASSWORD=userpassword
      - PROLOG_SERVER_URL=http://prolog:8081
  
  frontend:
    image: node:20.18.0-alpine
    container_name: aicare_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  mysql:
    image: mysql:8.0
    container_name: aicare_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=aicare
      - MYSQL_USER=aicareuser
      - MYSQL_PASSWORD=userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  prolog:
    image: swipl:latest
    container_name: aicare_prolog
    working_dir: /app
    volumes:
      - ./prolog:/app
    ports:
      - "8081:8081"
    command: swipl -s server.pl -g "server(8081), thread_get_message(quit)"

volumes:
  mysql_data:
    driver: local
