POST http://localhost:8000/predict
Content-Type: application/json

{
  "Age": 65,
  "Gender": 1,
  "Ethnicity": 2,
  "BMI": 24.5,
  "Smoking": 0,
  "AlcoholConsumption": 1.8,
  "PhysicalActivity": 3.5,
  "DietQuality": 4.0,
  "SleepQuality": 3.0,
  "Hypertension": 1,
  "Diabetes": 0,
  "Depression": 1,
  "SystolicBP": 130,
  "DiastolicBP": 85,
  "CholesterolTotal": 220.0,
  "CholesterolLDL": 140.0,
  "CholesterolHDL": 50.0,
  "CholesterolTriglycerides": 180.0,
  "FunctionalAssessment": 3.0,

  "FamilyHistoryParkinsons": 1,
  "TraumaticBrainInjury": 0,
  "Stroke": 0,
  "UPDRS": 32.0,
  "MoCA": 28.0,
  "Tremor": 1,
  "Rigidity": 1,
  "Bradykinesia": 1,
  "PosturalInstability": 0,
  "SpeechProblems": 0,
  "SleepDisorders": 1,
  "Constipation": 1,

  "FamilyHistoryAlzheimers": 1,
  "CardiovascularDisease": 1,
  "HeadInjury": 0,
  "MMSE": 26.0,
  "MemoryComplaints": 1,
  "BehavioralProblems": 0,
  "ADL": 4.0,
  "Confusion": 0,
  "Disorientation": 0,
  "PersonalityChanges": 1,
  "DifficultyCompletingTasks": 1,
  "Forgetfulness": 1
}